[book]
authors = ["Nelson Fonkoua"]
language = "en"
multilingual = false
src = "src"
title = "The Marcel Programming Language"
# https://rust-lang.github.io/mdBook/

[output.html]
git-repository-url = "https://github.com/tambapps/marcel"
