// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/flex/Marcel.flex

package com.tambapps.marcel.lexer;
import static com.tambapps.marcel.lexer.TokenType.*;
import java.util.Stack;

/**
  * Marcel lang lexer
  */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class MarcelJflexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int RAW_STRING = 4;
  public static final int SHORT_TEMPLATE_ENTRY = 6;
  public static final int BLOCK_COMMENT = 8;
  public static final int DOC_COMMENT = 10;
  public static final int LONG_TEMPLATE_ENTRY = 12;
  public static final int UNMATCHED_BACKTICK = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  4,  4,  5,  5,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\23\0\1\1\1\3"+
    "\1\4\1\0\1\5\1\6\1\7\1\0\1\10\1\11"+
    "\1\12\1\13\1\0\1\14\1\15\1\16\1\17\11\20"+
    "\1\21\1\22\1\23\1\24\1\25\2\0\1\26\1\27"+
    "\4\26\5\30\1\31\10\30\1\32\2\30\1\33\2\30"+
    "\1\0\1\34\2\0\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\2\30\1\50"+
    "\1\51\1\52\1\53\1\54\1\30\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\33\1\63\1\30\1\64\1\65"+
    "\1\66\54\0\1\30\12\0\1\30\4\0\1\30\5\0"+
    "\27\30\1\0\37\30\1\0\u01ca\30\4\0\14\30\16\0"+
    "\5\30\7\0\1\30\1\0\1\30\201\0\5\30\1\0"+
    "\2\30\2\0\4\30\1\0\1\30\6\0\1\30\1\0"+
    "\3\30\1\0\1\30\1\0\24\30\1\0\123\30\1\0"+
    "\213\30\10\0\246\30\1\0\46\30\2\0\1\30\6\0"+
    "\51\30\107\0\33\30\4\0\4\30\55\0\53\30\25\0"+
    "\12\67\4\0\2\30\1\0\143\30\1\0\1\30\17\0"+
    "\2\30\7\0\2\30\12\67\3\30\2\0\1\30\20\0"+
    "\1\30\1\0\36\30\35\0\131\30\13\0\1\30\16\0"+
    "\12\67\41\30\11\0\2\30\4\0\1\30\5\0\26\30"+
    "\4\0\1\30\11\0\1\30\3\0\1\30\27\0\31\30"+
    "\7\0\13\30\65\0\25\30\1\0\10\30\106\0\66\30"+
    "\3\0\1\30\22\0\1\30\7\0\12\30\4\0\12\67"+
    "\1\0\20\30\4\0\10\30\2\0\2\30\2\0\26\30"+
    "\1\0\7\30\1\0\1\30\3\0\4\30\3\0\1\30"+
    "\20\0\1\30\15\0\2\30\1\0\3\30\4\0\12\67"+
    "\2\30\12\0\1\30\10\0\6\30\4\0\2\30\2\0"+
    "\26\30\1\0\7\30\1\0\2\30\1\0\2\30\1\0"+
    "\2\30\37\0\4\30\1\0\1\30\7\0\12\67\2\0"+
    "\3\30\20\0\11\30\1\0\3\30\1\0\26\30\1\0"+
    "\7\30\1\0\2\30\1\0\5\30\3\0\1\30\22\0"+
    "\1\30\17\0\2\30\4\0\12\67\11\0\1\30\13\0"+
    "\10\30\2\0\2\30\2\0\26\30\1\0\7\30\1\0"+
    "\2\30\1\0\5\30\3\0\1\30\36\0\2\30\1\0"+
    "\3\30\4\0\12\67\1\0\1\30\21\0\1\30\1\0"+
    "\6\30\3\0\3\30\1\0\4\30\3\0\2\30\1\0"+
    "\1\30\1\0\2\30\3\0\2\30\3\0\3\30\3\0"+
    "\14\30\26\0\1\30\25\0\12\67\25\0\10\30\1\0"+
    "\3\30\1\0\27\30\1\0\20\30\3\0\1\30\32\0"+
    "\3\30\5\0\2\30\4\0\12\67\20\0\1\30\4\0"+
    "\10\30\1\0\3\30\1\0\27\30\1\0\12\30\1\0"+
    "\5\30\3\0\1\30\40\0\1\30\1\0\2\30\4\0"+
    "\12\67\1\0\2\30\22\0\10\30\1\0\3\30\1\0"+
    "\51\30\2\0\1\30\20\0\1\30\5\0\3\30\10\0"+
    "\3\30\4\0\12\67\12\0\6\30\5\0\22\30\3\0"+
    "\30\30\1\0\11\30\1\0\1\30\2\0\7\30\37\0"+
    "\12\67\21\0\60\30\1\0\2\30\14\0\7\30\11\0"+
    "\12\67\47\0\2\30\1\0\1\30\1\0\5\30\1\0"+
    "\30\30\1\0\1\30\1\0\12\30\1\0\2\30\11\0"+
    "\1\30\2\0\5\30\1\0\1\30\11\0\12\67\2\0"+
    "\4\30\40\0\1\30\37\0\12\67\26\0\10\30\1\0"+
    "\44\30\33\0\5\30\163\0\53\30\24\0\1\30\12\67"+
    "\6\0\6\30\4\0\4\30\3\0\1\30\3\0\2\30"+
    "\7\0\3\30\4\0\15\30\14\0\1\30\1\0\12\67"+
    "\6\0\46\30\1\0\1\30\5\0\1\30\2\0\53\30"+
    "\1\0\115\30\1\0\4\30\2\0\7\30\1\0\1\30"+
    "\1\0\4\30\2\0\51\30\1\0\4\30\2\0\41\30"+
    "\1\0\4\30\2\0\7\30\1\0\1\30\1\0\4\30"+
    "\2\0\17\30\1\0\71\30\1\0\4\30\2\0\103\30"+
    "\45\0\20\30\20\0\126\30\2\0\6\30\3\0\u016c\30"+
    "\2\0\21\30\1\0\32\30\5\0\113\30\6\0\10\30"+
    "\7\0\15\30\1\0\4\30\16\0\22\30\16\0\22\30"+
    "\16\0\15\30\1\0\3\30\17\0\64\30\43\0\1\30"+
    "\4\0\1\30\3\0\12\67\46\0\12\67\6\0\131\30"+
    "\7\0\5\30\2\0\42\30\1\0\1\30\5\0\106\30"+
    "\12\0\37\30\47\0\12\67\36\30\2\0\5\30\13\0"+
    "\54\30\4\0\32\30\6\0\12\67\46\0\27\30\11\0"+
    "\65\30\53\0\12\67\6\0\12\67\15\0\1\30\135\0"+
    "\57\30\21\0\7\30\4\0\12\67\51\0\36\30\15\0"+
    "\2\30\12\67\54\30\32\0\44\30\34\0\12\67\3\0"+
    "\3\30\12\67\44\30\2\0\11\30\7\0\53\30\2\0"+
    "\3\30\51\0\4\30\1\0\6\30\1\0\2\30\3\0"+
    "\1\30\5\0\300\30\100\0\26\30\2\0\6\30\2\0"+
    "\46\30\2\0\6\30\2\0\10\30\1\0\1\30\1\0"+
    "\1\30\1\0\1\30\1\0\37\30\2\0\65\30\1\0"+
    "\7\30\1\0\1\30\3\0\3\30\1\0\7\30\3\0"+
    "\4\30\2\0\6\30\4\0\15\30\5\0\3\30\1\0"+
    "\7\30\164\0\1\30\15\0\1\30\20\0\15\30\145\0"+
    "\1\30\4\0\1\30\2\0\12\30\1\0\1\30\3\0"+
    "\5\30\6\0\1\30\1\0\1\30\1\0\1\30\1\0"+
    "\4\30\1\0\13\30\2\0\4\30\5\0\5\30\4\0"+
    "\1\30\64\0\2\30\u017b\0\57\30\1\0\57\30\1\0"+
    "\205\30\6\0\4\30\3\0\2\30\14\0\46\30\1\0"+
    "\1\30\5\0\1\30\2\0\70\30\7\0\1\30\20\0"+
    "\27\30\11\0\7\30\1\0\7\30\1\0\7\30\1\0"+
    "\7\30\1\0\7\30\1\0\7\30\1\0\7\30\1\0"+
    "\7\30\120\0\1\30\325\0\2\30\52\0\5\30\5\0"+
    "\2\30\4\0\126\30\6\0\3\30\1\0\132\30\1\0"+
    "\4\30\5\0\53\30\1\0\136\30\21\0\33\30\65\0"+
    "\306\30\112\0\360\30\20\0\215\30\103\0\56\30\2\0"+
    "\15\30\3\0\20\30\12\67\2\30\24\0\57\30\20\0"+
    "\37\30\2\0\106\30\61\0\11\30\2\0\147\30\2\0"+
    "\65\30\2\0\5\30\60\0\13\30\1\0\3\30\1\0"+
    "\4\30\1\0\27\30\35\0\64\30\16\0\62\30\34\0"+
    "\12\67\30\0\6\30\3\0\1\30\1\0\2\30\1\0"+
    "\12\67\34\30\12\0\27\30\31\0\35\30\7\0\57\30"+
    "\34\0\1\30\12\67\6\0\5\30\1\0\12\30\12\67"+
    "\5\30\1\0\51\30\27\0\3\30\1\0\10\30\4\0"+
    "\12\67\6\0\27\30\3\0\1\30\3\0\62\30\1\0"+
    "\1\30\3\0\2\30\2\0\5\30\2\0\1\30\1\0"+
    "\1\30\30\0\3\30\2\0\13\30\7\0\3\30\14\0"+
    "\6\30\2\0\6\30\2\0\6\30\11\0\7\30\1\0"+
    "\7\30\1\0\53\30\1\0\14\30\10\0\163\30\15\0"+
    "\12\67\6\0\244\30\14\0\27\30\4\0\61\30\4\0"+
    "\156\30\2\0\152\30\46\0\7\30\14\0\5\30\5\0"+
    "\1\30\1\0\12\30\1\0\15\30\1\0\5\30\1\0"+
    "\1\30\1\0\2\30\1\0\2\30\1\0\154\30\41\0"+
    "\153\30\22\0\100\30\2\0\66\30\50\0\14\30\164\0"+
    "\5\30\1\0\207\30\23\0\12\67\7\0\32\30\6\0"+
    "\32\30\13\0\131\30\3\0\6\30\2\0\6\30\2\0"+
    "\6\30\2\0\3\30\43\0\14\30\1\0\32\30\1\0"+
    "\23\30\1\0\2\30\1\0\17\30\2\0\16\30\42\0"+
    "\173\30\205\0\35\30\3\0\61\30\57\0\40\30\15\0"+
    "\24\30\1\0\10\30\6\0\46\30\12\0\36\30\2\0"+
    "\44\30\4\0\10\30\60\0\236\30\2\0\12\67\6\0"+
    "\44\30\4\0\44\30\4\0\50\30\10\0\64\30\234\0"+
    "\67\30\11\0\26\30\12\0\10\30\230\0\6\30\2\0"+
    "\1\30\1\0\54\30\1\0\2\30\3\0\1\30\2\0"+
    "\27\30\12\0\27\30\11\0\37\30\101\0\23\30\1\0"+
    "\2\30\12\0\26\30\12\0\32\30\106\0\70\30\6\0"+
    "\2\30\100\0\1\30\17\0\4\30\1\0\3\30\1\0"+
    "\35\30\52\0\35\30\3\0\35\30\43\0\10\30\1\0"+
    "\34\30\33\0\66\30\12\0\26\30\12\0\23\30\15\0"+
    "\22\30\156\0\111\30\67\0\63\30\15\0\63\30\15\0"+
    "\44\30\14\0\12\67\306\0\35\30\12\0\1\30\10\0"+
    "\26\30\232\0\27\30\14\0\65\30\56\0\12\67\23\0"+
    "\55\30\40\0\31\30\7\0\12\67\11\0\44\30\17\0"+
    "\12\67\4\0\1\30\13\0\43\30\3\0\1\30\14\0"+
    "\60\30\16\0\4\30\13\0\12\67\1\30\1\0\1\30"+
    "\43\0\22\30\1\0\31\30\124\0\7\30\1\0\1\30"+
    "\1\0\4\30\1\0\17\30\1\0\12\30\7\0\57\30"+
    "\21\0\12\67\13\0\10\30\2\0\2\30\2\0\26\30"+
    "\1\0\7\30\1\0\2\30\1\0\5\30\3\0\1\30"+
    "\22\0\1\30\14\0\5\30\236\0\65\30\22\0\4\30"+
    "\5\0\12\67\5\0\1\30\40\0\60\30\24\0\2\30"+
    "\1\0\1\30\10\0\12\67\246\0\57\30\51\0\4\30"+
    "\44\0\60\30\24\0\1\30\13\0\12\67\46\0\53\30"+
    "\15\0\1\30\7\0\12\67\66\0\33\30\25\0\12\67"+
    "\306\0\54\30\164\0\100\30\12\67\25\0\1\30\240\0"+
    "\10\30\2\0\47\30\20\0\1\30\1\0\1\30\34\0"+
    "\1\30\12\0\50\30\7\0\1\30\25\0\1\30\13\0"+
    "\56\30\23\0\1\30\42\0\71\30\7\0\11\30\1\0"+
    "\45\30\21\0\1\30\17\0\12\67\30\0\36\30\160\0"+
    "\7\30\1\0\2\30\1\0\46\30\25\0\1\30\11\0"+
    "\12\67\6\0\6\30\1\0\2\30\1\0\40\30\16\0"+
    "\1\30\7\0\12\67\u0136\0\23\30\15\0\232\30\346\0"+
    "\304\30\274\0\57\30\321\0\107\30\271\0\71\30\7\0"+
    "\37\30\1\0\12\67\146\0\36\30\22\0\60\30\20\0"+
    "\4\30\14\0\12\67\11\0\25\30\5\0\23\30\260\0"+
    "\100\30\200\0\113\30\5\0\1\30\102\0\15\30\100\0"+
    "\2\30\1\0\1\30\34\0\370\30\10\0\363\30\15\0"+
    "\37\30\61\0\3\30\21\0\4\30\10\0\u018c\30\4\0"+
    "\153\30\5\0\15\30\3\0\11\30\7\0\12\30\146\0"+
    "\125\30\1\0\107\30\1\0\2\30\2\0\1\30\2\0"+
    "\2\30\2\0\4\30\1\0\14\30\1\0\1\30\1\0"+
    "\7\30\1\0\101\30\1\0\4\30\2\0\10\30\1\0"+
    "\7\30\1\0\34\30\1\0\4\30\1\0\5\30\1\0"+
    "\1\30\3\0\7\30\1\0\u0154\30\2\0\31\30\1\0"+
    "\31\30\1\0\37\30\1\0\31\30\1\0\37\30\1\0"+
    "\31\30\1\0\37\30\1\0\31\30\1\0\37\30\1\0"+
    "\31\30\1\0\10\30\2\0\62\67\55\30\12\0\7\30"+
    "\2\0\12\67\4\0\1\30\u0171\0\54\30\4\0\12\67"+
    "\6\0\305\30\73\0\104\30\7\0\1\30\4\0\12\67"+
    "\246\0\4\30\1\0\33\30\1\0\2\30\1\0\1\30"+
    "\2\0\1\30\1\0\12\30\1\0\4\30\1\0\1\30"+
    "\1\0\1\30\6\0\1\30\4\0\1\30\1\0\1\30"+
    "\1\0\1\30\1\0\3\30\1\0\2\30\1\0\1\30"+
    "\2\0\1\30\1\0\1\30\1\0\1\30\1\0\1\30"+
    "\1\0\1\30\1\0\2\30\1\0\1\30\2\0\4\30"+
    "\1\0\7\30\1\0\4\30\1\0\4\30\1\0\1\30"+
    "\1\0\12\30\1\0\21\30\5\0\3\30\1\0\5\30"+
    "\1\0\21\30\104\0\327\30\51\0\65\30\13\0\336\30"+
    "\2\0\u0182\30\16\0\u0131\30\37\0\36\30\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\1\3\1\4\1\0\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\0\15\22\1\23\1\0"+
    "\1\24\1\25\1\26\1\27\1\25\1\0\2\25\1\30"+
    "\1\0\1\31\1\32\1\33\1\0\1\34\3\14\1\35"+
    "\1\36\1\37\1\0\1\40\21\22\1\41\1\42\1\0"+
    "\1\43\2\44\2\0\1\45\6\22\1\46\2\22\1\47"+
    "\1\22\1\50\7\22\2\0\1\51\1\30\1\52\1\53"+
    "\5\22\1\54\5\22\1\55\1\56\1\42\1\0\1\22"+
    "\1\57\1\60\6\22\1\61\1\0\1\62\1\63\1\64"+
    "\2\22\1\65\1\66\1\67\2\22\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\340\0\u01f8\0\340\0\340\0\340\0\340\0\340"+
    "\0\340\0\340\0\u0230\0\u0268\0\340\0\340\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\340\0\u0690\0\340\0\u06c8\0\340\0\340\0\u0700\0\u0738"+
    "\0\340\0\u0770\0\u07a8\0\u07e0\0\340\0\340\0\340\0\u0818"+
    "\0\340\0\340\0\u0850\0\u0888\0\340\0\340\0\340\0\u08c0"+
    "\0\u0348\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08"+
    "\0\u0c40\0\u0c78\0\340\0\u0cb0\0\u0ce8\0\340\0\340\0\u0d20"+
    "\0\u0d58\0\u0d90\0\340\0\340\0\u0dc8\0\u0e00\0\u0e38\0\u0e70"+
    "\0\u0ea8\0\u0348\0\u0ee0\0\u0f18\0\u0348\0\u0f50\0\u0348\0\u0f88"+
    "\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148"+
    "\0\u0d58\0\340\0\u0348\0\u0348\0\u1180\0\u11b8\0\u11f0\0\u1228"+
    "\0\u1260\0\u0348\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u0348"+
    "\0\u0348\0\340\0\u13b0\0\u13e8\0\u0348\0\u0348\0\u1420\0\u1458"+
    "\0\u1490\0\u14c8\0\u1500\0\u1538\0\u0348\0\u1570\0\u0348\0\u0348"+
    "\0\u0348\0\u15a8\0\u15e0\0\u0348\0\u0348\0\u0348\0\u1618\0\u1650"+
    "\0\u0348";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\7\1\10\1\11\1\0\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\6\32\1\0\1\32"+
    "\1\33\1\34\1\35\1\32\1\36\1\32\1\37\1\32"+
    "\1\40\1\41\1\42\1\32\1\43\1\32\1\44\1\45"+
    "\1\46\1\47\1\32\1\50\2\32\1\51\1\52\1\53"+
    "\1\0\2\54\1\55\1\54\1\56\1\57\26\54\1\60"+
    "\35\54\1\61\1\54\1\62\1\57\26\54\1\61\33\54"+
    "\26\0\6\63\1\0\1\63\1\64\25\63\75\0\2\7"+
    "\1\10\1\11\1\0\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\6\32\1\0\1\32\1\33\1\34"+
    "\1\35\1\32\1\36\1\32\1\37\1\32\1\40\1\41"+
    "\1\42\1\32\1\43\1\32\1\44\1\45\1\46\1\47"+
    "\1\32\1\50\2\32\1\65\1\52\1\66\2\0\2\7"+
    "\111\0\1\67\47\0\1\70\72\0\1\71\107\0\1\24"+
    "\1\0\1\72\1\73\1\74\4\0\1\24\7\0\1\72"+
    "\7\0\1\73\26\0\2\24\10\0\1\72\1\73\2\0"+
    "\1\24\12\0\1\72\7\0\1\73\33\0\1\75\67\0"+
    "\1\76\67\0\1\77\62\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\25\32\3\0\1\32\2\100\1\0\33\100"+
    "\1\0\31\100\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\17\32\1\101\5\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\14\32\1\102\7\32"+
    "\1\103\3\0\1\32\17\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\14\32\1\104\10\32\3\0\1\32\17\0"+
    "\2\32\5\0\6\32\1\0\1\32\1\0\1\105\10\32"+
    "\1\106\7\32\1\107\3\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\10\32\1\110\14\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\12\32\1\111\1\112\11\32\3\0\1\32\17\0"+
    "\2\32\5\0\6\32\1\0\1\32\1\0\14\32\1\113"+
    "\10\32\3\0\1\32\17\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\4\32\1\114\20\32\3\0\1\32\17\0"+
    "\2\32\5\0\6\32\1\0\1\32\1\0\16\32\1\115"+
    "\2\32\1\116\3\32\3\0\1\32\17\0\2\32\5\0"+
    "\6\32\1\0\1\32\1\0\4\32\1\117\20\32\3\0"+
    "\1\32\17\0\2\32\5\0\6\32\1\0\1\32\1\0"+
    "\7\32\1\120\15\32\3\0\1\32\17\0\2\32\5\0"+
    "\6\32\1\0\1\32\1\0\16\32\1\121\6\32\3\0"+
    "\1\32\17\0\2\32\5\0\6\32\1\0\1\32\1\0"+
    "\14\32\1\122\10\32\3\0\1\32\65\0\1\123\2\0"+
    "\2\54\1\0\1\54\2\0\26\54\1\0\33\54\26\0"+
    "\6\124\1\0\1\124\1\125\25\124\1\126\3\0\2\127"+
    "\1\0\55\127\1\130\7\127\4\0\1\131\102\0\2\63"+
    "\5\0\6\63\1\0\1\63\1\0\25\63\3\0\1\63"+
    "\2\132\1\0\33\132\1\0\31\132\4\0\1\133\114\0"+
    "\1\72\16\0\1\72\36\0\2\74\5\0\2\74\1\0"+
    "\1\72\1\73\2\0\1\74\1\0\6\74\3\0\1\72"+
    "\7\0\1\73\7\0\2\100\1\0\33\100\1\134\31\100"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\14\32"+
    "\1\135\10\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\20\32\1\136\4\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\21\32"+
    "\1\137\3\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\11\32\1\140\13\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\14\32"+
    "\1\141\10\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\13\32\1\142\11\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\3\32"+
    "\1\143\21\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\15\32\1\144\7\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\20\32"+
    "\1\145\4\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\13\32\1\146\11\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\23\32"+
    "\1\147\1\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\10\32\1\150\3\32\1\151\10\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\1\32\1\152\23\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\20\32\1\153\4\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\14\32\1\154\10\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\21\32\1\155\3\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\10\32\1\156\14\32\3\0\1\32\17\0\2\124"+
    "\5\0\6\124\1\0\1\124\1\0\25\124\3\0\1\124"+
    "\2\157\1\0\33\157\1\0\31\157\17\0\2\160\5\0"+
    "\2\160\7\0\6\160\27\0\1\161\63\0\2\132\1\0"+
    "\33\132\1\162\31\132\17\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\11\32\1\163\13\32\3\0\1\32\17\0"+
    "\2\32\5\0\6\32\1\0\1\32\1\0\4\32\1\164"+
    "\20\32\3\0\1\32\17\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\1\32\1\165\23\32\3\0\1\32\17\0"+
    "\2\32\5\0\6\32\1\0\1\32\1\0\17\32\1\166"+
    "\5\32\3\0\1\32\17\0\2\32\5\0\6\32\1\0"+
    "\1\32\1\0\1\167\24\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\3\32\1\170\21\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\14\32\1\171\10\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\6\32\1\172\16\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\22\32\1\173\2\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\20\32\1\174\4\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\11\32\1\175\13\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\21\32\1\176\3\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\16\32\1\177\6\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\4\32\1\200\20\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\3\32\1\201\21\32\3\0\1\32\2\157\1\0"+
    "\33\157\1\202\31\157\17\0\2\203\5\0\2\203\7\0"+
    "\6\203\42\0\2\32\5\0\6\32\1\0\1\32\1\0"+
    "\11\32\1\204\13\32\3\0\1\32\17\0\2\32\5\0"+
    "\6\32\1\0\1\32\1\0\4\32\1\205\20\32\3\0"+
    "\1\32\17\0\2\32\5\0\6\32\1\0\1\32\1\0"+
    "\20\32\1\206\4\32\3\0\1\32\17\0\2\32\5\0"+
    "\6\32\1\0\1\32\1\0\4\32\1\207\20\32\3\0"+
    "\1\32\17\0\2\32\5\0\6\32\1\0\1\32\1\0"+
    "\16\32\1\210\6\32\3\0\1\32\17\0\2\32\5\0"+
    "\6\32\1\0\1\32\1\0\1\211\24\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\4\32"+
    "\1\212\20\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\10\32\1\213\14\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\16\32"+
    "\1\214\6\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\20\32\1\215\4\32\3\0\1\32"+
    "\17\0\2\216\5\0\2\216\7\0\6\216\42\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\4\32\1\217\20\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\13\32\1\220\11\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\20\32\1\221\4\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\20\32\1\222\4\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\2\32\1\223\22\32"+
    "\3\0\1\32\17\0\2\32\5\0\6\32\1\0\1\32"+
    "\1\0\2\32\1\224\22\32\3\0\1\32\17\0\2\32"+
    "\5\0\6\32\1\0\1\32\1\0\13\32\1\225\11\32"+
    "\3\0\1\32\17\0\2\127\5\0\2\127\7\0\6\127"+
    "\42\0\2\32\5\0\6\32\1\0\1\32\1\0\4\32"+
    "\1\226\20\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\20\32\1\227\4\32\3\0\1\32"+
    "\17\0\2\32\5\0\6\32\1\0\1\32\1\0\4\32"+
    "\1\230\20\32\3\0\1\32\17\0\2\32\5\0\6\32"+
    "\1\0\1\32\1\0\3\32\1\231\21\32\3\0\1\32";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5768];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\10\1\0\3\1\1\11\1\0\7\11\2\1"+
    "\2\11\4\1\1\0\15\1\1\11\1\0\1\11\1\1"+
    "\2\11\1\1\1\0\1\11\2\1\1\0\3\11\1\0"+
    "\2\11\2\1\3\11\1\0\22\1\1\11\1\1\1\0"+
    "\2\11\1\1\2\0\2\11\22\1\2\0\1\1\1\11"+
    "\17\1\1\11\1\0\12\1\1\0\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[153];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

     private static final class State {
            final int lBraceCount;
            final int state;

            public State(int state, int lBraceCount) {
                this.state = state;
                this.lBraceCount = lBraceCount;
            }

            @Override
            public String toString() {
                return "yystate = " + state + (lBraceCount == 0 ? "" : "lBraceCount = " + lBraceCount);
            }
        }

    private final Stack<State> states = new Stack<State>();
    private int lBraceCount;

    private int commentStart;
    private int commentDepth;

    private void pushState(int state) {
        states.push(new State(yystate(), lBraceCount));
        lBraceCount = 0;
        yybegin(state);
    }

    private void popState() {
        State state = states.pop();
        lBraceCount = state.lBraceCount;
        yybegin(state.state);
    }

  // tokens for which we need to save current buffer
  private LexToken valueToken(TokenType tokenType) {
    return new LexToken(tokenType, new String(zzBuffer, zzCurrentPos, zzMarkedPos - zzCurrentPos));
  }
  private LexToken token(TokenType tokenType) {
    return new LexToken(tokenType, null);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MarcelJflexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) throws MarcelLexerException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new MarcelLexerException(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  throws MarcelLexerException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  // end of file
    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LexToken nextToken() throws java.io.IOException, MarcelLexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(WHITE_SPACE);
            }
            // fall through
          case 57: break;
          case 2:
            { return token(NOT);
            }
            // fall through
          case 58: break;
          case 3:
            { pushState(STRING); return token(OPEN_QUOTE);
            }
            // fall through
          case 59: break;
          case 4:
            { return token(MODULO);
            }
            // fall through
          case 60: break;
          case 5:
            { return token(LPAR);
            }
            // fall through
          case 61: break;
          case 6:
            { return token(RPAR);
            }
            // fall through
          case 62: break;
          case 7:
            { return token(MUL);
            }
            // fall through
          case 63: break;
          case 8:
            { return token(PLUS);
            }
            // fall through
          case 64: break;
          case 9:
            { return token(MINUS);
            }
            // fall through
          case 65: break;
          case 10:
            { return token(DOT);
            }
            // fall through
          case 66: break;
          case 11:
            { return token(DIV);
            }
            // fall through
          case 67: break;
          case 12:
            { return valueToken(INTEGER);
            }
            // fall through
          case 68: break;
          case 13:
            { return token(COLON);
            }
            // fall through
          case 69: break;
          case 14:
            { return token(SEMI_COLON);
            }
            // fall through
          case 70: break;
          case 15:
            { return token(LT);
            }
            // fall through
          case 71: break;
          case 16:
            { return token(ASSIGNMENT);
            }
            // fall through
          case 72: break;
          case 17:
            { return token(GT);
            }
            // fall through
          case 73: break;
          case 18:
            { return valueToken(IDENTIFIER);
            }
            // fall through
          case 74: break;
          case 19:
            { return token(BRACKETS_OPEN);
            }
            // fall through
          case 75: break;
          case 20:
            { return token(BRACKETS_CLOSE);
            }
            // fall through
          case 76: break;
          case 21:
            { return valueToken(REGULAR_STRING_PART);
            }
            // fall through
          case 77: break;
          case 22:
            { popState(); yypushback(1); return valueToken(DANGLING_NEWLINE);
            }
            // fall through
          case 78: break;
          case 23:
            { popState(); return token(CLOSING_QUOTE);
            }
            // fall through
          case 79: break;
          case 24:
            { popState(); return valueToken(IDENTIFIER);
            }
            // fall through
          case 80: break;
          case 25:
            { lBraceCount++; return valueToken(LBRACE);
            }
            // fall through
          case 81: break;
          case 26:
            { if (lBraceCount == 0) {
                                             popState();
                                             return token(LONG_TEMPLATE_ENTRY_END);
                                           }
                                           lBraceCount--;
                                           return valueToken(RBRACE);
            }
            // fall through
          case 82: break;
          case 27:
            { return token(NOT_EQUAL);
            }
            // fall through
          case 83: break;
          case 28:
            { return token(AND);
            }
            // fall through
          case 84: break;
          case 29:
            { return token(LOE);
            }
            // fall through
          case 85: break;
          case 30:
            { return token(EQUAL);
            }
            // fall through
          case 86: break;
          case 31:
            { return token(GOE);
            }
            // fall through
          case 87: break;
          case 32:
            { return token(AS);
            }
            // fall through
          case 88: break;
          case 33:
            { return token(OR);
            }
            // fall through
          case 89: break;
          case 34:
            { pushState(SHORT_TEMPLATE_ENTRY);
                                                        yypushback(yylength() - 1);
                                                        return token(SHORT_TEMPLATE_ENTRY_START);
            }
            // fall through
          case 90: break;
          case 35:
            { pushState(LONG_TEMPLATE_ENTRY); return token(LONG_TEMPLATE_ENTRY_START);
            }
            // fall through
          case 91: break;
          case 36:
            { return valueToken(ESCAPE_SEQUENCE);
            }
            // fall through
          case 92: break;
          case 37:
            { pushState(RAW_STRING); return token(OPEN_QUOTE);
            }
            // fall through
          case 93: break;
          case 38:
            { return token(FUN);
            }
            // fall through
          case 94: break;
          case 39:
            { return token(TYPE_INT);
            }
            // fall through
          case 95: break;
          case 40:
            { return token(NEW);
            }
            // fall through
          case 96: break;
          case 41:
            { int length = yytext().length();
                                    if (length <= 3) { // closing """
                                        popState();
                                        return token(CLOSING_QUOTE);
                                    }
                                    else { // some quotes at the end of a string, e.g. """ "foo""""
                                        yypushback(3); // return the closing quotes (""") to the stream
                                        return valueToken(REGULAR_STRING_PART);
                                    }
            }
            // fall through
          case 97: break;
          case 42:
            { return token(TYPE_BOOL);
            }
            // fall through
          case 98: break;
          case 43:
            { return token(TYPE_BYTE);
            }
            // fall through
          case 99: break;
          case 44:
            { return token(TYPE_LONG);
            }
            // fall through
          case 100: break;
          case 45:
            { return token(VALUE_TRUE);
            }
            // fall through
          case 101: break;
          case 46:
            { return token(TYPE_VOID);
            }
            // fall through
          case 102: break;
          case 47:
            { return token(VALUE_FALSE);
            }
            // fall through
          case 103: break;
          case 48:
            { return token(TYPE_FLOAT);
            }
            // fall through
          case 104: break;
          case 49:
            { return token(TYPE_SHORT);
            }
            // fall through
          case 105: break;
          case 50:
            { return token(TYPE_DOUBLE);
            }
            // fall through
          case 106: break;
          case 51:
            { return token(VISIBILITY_HIDDEN);
            }
            // fall through
          case 107: break;
          case 52:
            { return token(IMPORT);
            }
            // fall through
          case 108: break;
          case 53:
            { return token(VISIBILITY_PUBLIC);
            }
            // fall through
          case 109: break;
          case 54:
            { return token(RETURN);
            }
            // fall through
          case 110: break;
          case 55:
            { return token(VISIBILITY_PRIVATE);
            }
            // fall through
          case 111: break;
          case 56:
            { return token(VISIBILITY_PROTECTED);
            }
            // fall through
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
