// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/flex/Marcel.flex

package com.tambapps.marcel.lexer;
import static com.tambapps.marcel.lexer.TokenType.*;
import java.util.Stack;

/**
  * Marcel lang lexer
  */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class MarcelJflexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int RAW_STRING = 4;
  public static final int SHORT_TEMPLATE_ENTRY = 6;
  public static final int BLOCK_COMMENT = 8;
  public static final int DOC_COMMENT = 10;
  public static final int LONG_TEMPLATE_ENTRY = 12;
  public static final int UNMATCHED_BACKTICK = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  4,  4,  5,  5,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\23\0\1\1\1\0"+
    "\1\3\1\0\1\4\3\0\1\5\1\6\1\7\1\10"+
    "\1\0\1\11\1\0\1\12\1\13\11\14\1\15\1\16"+
    "\1\0\1\17\3\0\1\20\1\21\4\20\5\22\1\23"+
    "\10\22\1\24\2\22\1\25\2\22\1\0\1\26\2\0"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\2\22\1\42\1\22\1\43\1\44"+
    "\1\45\1\22\1\46\1\47\1\50\1\51\1\52\1\22"+
    "\1\25\1\53\1\22\1\54\1\0\1\55\54\0\1\22"+
    "\12\0\1\22\4\0\1\22\5\0\27\22\1\0\37\22"+
    "\1\0\u01ca\22\4\0\14\22\16\0\5\22\7\0\1\22"+
    "\1\0\1\22\201\0\5\22\1\0\2\22\2\0\4\22"+
    "\1\0\1\22\6\0\1\22\1\0\3\22\1\0\1\22"+
    "\1\0\24\22\1\0\123\22\1\0\213\22\10\0\246\22"+
    "\1\0\46\22\2\0\1\22\6\0\51\22\107\0\33\22"+
    "\4\0\4\22\55\0\53\22\25\0\12\56\4\0\2\22"+
    "\1\0\143\22\1\0\1\22\17\0\2\22\7\0\2\22"+
    "\12\56\3\22\2\0\1\22\20\0\1\22\1\0\36\22"+
    "\35\0\131\22\13\0\1\22\16\0\12\56\41\22\11\0"+
    "\2\22\4\0\1\22\5\0\26\22\4\0\1\22\11\0"+
    "\1\22\3\0\1\22\27\0\31\22\7\0\13\22\65\0"+
    "\25\22\1\0\10\22\106\0\66\22\3\0\1\22\22\0"+
    "\1\22\7\0\12\22\4\0\12\56\1\0\20\22\4\0"+
    "\10\22\2\0\2\22\2\0\26\22\1\0\7\22\1\0"+
    "\1\22\3\0\4\22\3\0\1\22\20\0\1\22\15\0"+
    "\2\22\1\0\3\22\4\0\12\56\2\22\12\0\1\22"+
    "\10\0\6\22\4\0\2\22\2\0\26\22\1\0\7\22"+
    "\1\0\2\22\1\0\2\22\1\0\2\22\37\0\4\22"+
    "\1\0\1\22\7\0\12\56\2\0\3\22\20\0\11\22"+
    "\1\0\3\22\1\0\26\22\1\0\7\22\1\0\2\22"+
    "\1\0\5\22\3\0\1\22\22\0\1\22\17\0\2\22"+
    "\4\0\12\56\11\0\1\22\13\0\10\22\2\0\2\22"+
    "\2\0\26\22\1\0\7\22\1\0\2\22\1\0\5\22"+
    "\3\0\1\22\36\0\2\22\1\0\3\22\4\0\12\56"+
    "\1\0\1\22\21\0\1\22\1\0\6\22\3\0\3\22"+
    "\1\0\4\22\3\0\2\22\1\0\1\22\1\0\2\22"+
    "\3\0\2\22\3\0\3\22\3\0\14\22\26\0\1\22"+
    "\25\0\12\56\25\0\10\22\1\0\3\22\1\0\27\22"+
    "\1\0\20\22\3\0\1\22\32\0\3\22\5\0\2\22"+
    "\4\0\12\56\20\0\1\22\4\0\10\22\1\0\3\22"+
    "\1\0\27\22\1\0\12\22\1\0\5\22\3\0\1\22"+
    "\40\0\1\22\1\0\2\22\4\0\12\56\1\0\2\22"+
    "\22\0\10\22\1\0\3\22\1\0\51\22\2\0\1\22"+
    "\20\0\1\22\5\0\3\22\10\0\3\22\4\0\12\56"+
    "\12\0\6\22\5\0\22\22\3\0\30\22\1\0\11\22"+
    "\1\0\1\22\2\0\7\22\37\0\12\56\21\0\60\22"+
    "\1\0\2\22\14\0\7\22\11\0\12\56\47\0\2\22"+
    "\1\0\1\22\1\0\5\22\1\0\30\22\1\0\1\22"+
    "\1\0\12\22\1\0\2\22\11\0\1\22\2\0\5\22"+
    "\1\0\1\22\11\0\12\56\2\0\4\22\40\0\1\22"+
    "\37\0\12\56\26\0\10\22\1\0\44\22\33\0\5\22"+
    "\163\0\53\22\24\0\1\22\12\56\6\0\6\22\4\0"+
    "\4\22\3\0\1\22\3\0\2\22\7\0\3\22\4\0"+
    "\15\22\14\0\1\22\1\0\12\56\6\0\46\22\1\0"+
    "\1\22\5\0\1\22\2\0\53\22\1\0\115\22\1\0"+
    "\4\22\2\0\7\22\1\0\1\22\1\0\4\22\2\0"+
    "\51\22\1\0\4\22\2\0\41\22\1\0\4\22\2\0"+
    "\7\22\1\0\1\22\1\0\4\22\2\0\17\22\1\0"+
    "\71\22\1\0\4\22\2\0\103\22\45\0\20\22\20\0"+
    "\126\22\2\0\6\22\3\0\u016c\22\2\0\21\22\1\0"+
    "\32\22\5\0\113\22\6\0\10\22\7\0\15\22\1\0"+
    "\4\22\16\0\22\22\16\0\22\22\16\0\15\22\1\0"+
    "\3\22\17\0\64\22\43\0\1\22\4\0\1\22\3\0"+
    "\12\56\46\0\12\56\6\0\131\22\7\0\5\22\2\0"+
    "\42\22\1\0\1\22\5\0\106\22\12\0\37\22\47\0"+
    "\12\56\36\22\2\0\5\22\13\0\54\22\4\0\32\22"+
    "\6\0\12\56\46\0\27\22\11\0\65\22\53\0\12\56"+
    "\6\0\12\56\15\0\1\22\135\0\57\22\21\0\7\22"+
    "\4\0\12\56\51\0\36\22\15\0\2\22\12\56\54\22"+
    "\32\0\44\22\34\0\12\56\3\0\3\22\12\56\44\22"+
    "\2\0\11\22\7\0\53\22\2\0\3\22\51\0\4\22"+
    "\1\0\6\22\1\0\2\22\3\0\1\22\5\0\300\22"+
    "\100\0\26\22\2\0\6\22\2\0\46\22\2\0\6\22"+
    "\2\0\10\22\1\0\1\22\1\0\1\22\1\0\1\22"+
    "\1\0\37\22\2\0\65\22\1\0\7\22\1\0\1\22"+
    "\3\0\3\22\1\0\7\22\3\0\4\22\2\0\6\22"+
    "\4\0\15\22\5\0\3\22\1\0\7\22\164\0\1\22"+
    "\15\0\1\22\20\0\15\22\145\0\1\22\4\0\1\22"+
    "\2\0\12\22\1\0\1\22\3\0\5\22\6\0\1\22"+
    "\1\0\1\22\1\0\1\22\1\0\4\22\1\0\13\22"+
    "\2\0\4\22\5\0\5\22\4\0\1\22\64\0\2\22"+
    "\u017b\0\57\22\1\0\57\22\1\0\205\22\6\0\4\22"+
    "\3\0\2\22\14\0\46\22\1\0\1\22\5\0\1\22"+
    "\2\0\70\22\7\0\1\22\20\0\27\22\11\0\7\22"+
    "\1\0\7\22\1\0\7\22\1\0\7\22\1\0\7\22"+
    "\1\0\7\22\1\0\7\22\1\0\7\22\120\0\1\22"+
    "\325\0\2\22\52\0\5\22\5\0\2\22\4\0\126\22"+
    "\6\0\3\22\1\0\132\22\1\0\4\22\5\0\53\22"+
    "\1\0\136\22\21\0\33\22\65\0\306\22\112\0\360\22"+
    "\20\0\215\22\103\0\56\22\2\0\15\22\3\0\20\22"+
    "\12\56\2\22\24\0\57\22\20\0\37\22\2\0\106\22"+
    "\61\0\11\22\2\0\147\22\2\0\65\22\2\0\5\22"+
    "\60\0\13\22\1\0\3\22\1\0\4\22\1\0\27\22"+
    "\35\0\64\22\16\0\62\22\34\0\12\56\30\0\6\22"+
    "\3\0\1\22\1\0\2\22\1\0\12\56\34\22\12\0"+
    "\27\22\31\0\35\22\7\0\57\22\34\0\1\22\12\56"+
    "\6\0\5\22\1\0\12\22\12\56\5\22\1\0\51\22"+
    "\27\0\3\22\1\0\10\22\4\0\12\56\6\0\27\22"+
    "\3\0\1\22\3\0\62\22\1\0\1\22\3\0\2\22"+
    "\2\0\5\22\2\0\1\22\1\0\1\22\30\0\3\22"+
    "\2\0\13\22\7\0\3\22\14\0\6\22\2\0\6\22"+
    "\2\0\6\22\11\0\7\22\1\0\7\22\1\0\53\22"+
    "\1\0\14\22\10\0\163\22\15\0\12\56\6\0\244\22"+
    "\14\0\27\22\4\0\61\22\4\0\156\22\2\0\152\22"+
    "\46\0\7\22\14\0\5\22\5\0\1\22\1\0\12\22"+
    "\1\0\15\22\1\0\5\22\1\0\1\22\1\0\2\22"+
    "\1\0\2\22\1\0\154\22\41\0\153\22\22\0\100\22"+
    "\2\0\66\22\50\0\14\22\164\0\5\22\1\0\207\22"+
    "\23\0\12\56\7\0\32\22\6\0\32\22\13\0\131\22"+
    "\3\0\6\22\2\0\6\22\2\0\6\22\2\0\3\22"+
    "\43\0\14\22\1\0\32\22\1\0\23\22\1\0\2\22"+
    "\1\0\17\22\2\0\16\22\42\0\173\22\205\0\35\22"+
    "\3\0\61\22\57\0\40\22\15\0\24\22\1\0\10\22"+
    "\6\0\46\22\12\0\36\22\2\0\44\22\4\0\10\22"+
    "\60\0\236\22\2\0\12\56\6\0\44\22\4\0\44\22"+
    "\4\0\50\22\10\0\64\22\234\0\67\22\11\0\26\22"+
    "\12\0\10\22\230\0\6\22\2\0\1\22\1\0\54\22"+
    "\1\0\2\22\3\0\1\22\2\0\27\22\12\0\27\22"+
    "\11\0\37\22\101\0\23\22\1\0\2\22\12\0\26\22"+
    "\12\0\32\22\106\0\70\22\6\0\2\22\100\0\1\22"+
    "\17\0\4\22\1\0\3\22\1\0\35\22\52\0\35\22"+
    "\3\0\35\22\43\0\10\22\1\0\34\22\33\0\66\22"+
    "\12\0\26\22\12\0\23\22\15\0\22\22\156\0\111\22"+
    "\67\0\63\22\15\0\63\22\15\0\44\22\14\0\12\56"+
    "\306\0\35\22\12\0\1\22\10\0\26\22\232\0\27\22"+
    "\14\0\65\22\56\0\12\56\23\0\55\22\40\0\31\22"+
    "\7\0\12\56\11\0\44\22\17\0\12\56\4\0\1\22"+
    "\13\0\43\22\3\0\1\22\14\0\60\22\16\0\4\22"+
    "\13\0\12\56\1\22\1\0\1\22\43\0\22\22\1\0"+
    "\31\22\124\0\7\22\1\0\1\22\1\0\4\22\1\0"+
    "\17\22\1\0\12\22\7\0\57\22\21\0\12\56\13\0"+
    "\10\22\2\0\2\22\2\0\26\22\1\0\7\22\1\0"+
    "\2\22\1\0\5\22\3\0\1\22\22\0\1\22\14\0"+
    "\5\22\236\0\65\22\22\0\4\22\5\0\12\56\5\0"+
    "\1\22\40\0\60\22\24\0\2\22\1\0\1\22\10\0"+
    "\12\56\246\0\57\22\51\0\4\22\44\0\60\22\24\0"+
    "\1\22\13\0\12\56\46\0\53\22\15\0\1\22\7\0"+
    "\12\56\66\0\33\22\25\0\12\56\306\0\54\22\164\0"+
    "\100\22\12\56\25\0\1\22\240\0\10\22\2\0\47\22"+
    "\20\0\1\22\1\0\1\22\34\0\1\22\12\0\50\22"+
    "\7\0\1\22\25\0\1\22\13\0\56\22\23\0\1\22"+
    "\42\0\71\22\7\0\11\22\1\0\45\22\21\0\1\22"+
    "\17\0\12\56\30\0\36\22\160\0\7\22\1\0\2\22"+
    "\1\0\46\22\25\0\1\22\11\0\12\56\6\0\6\22"+
    "\1\0\2\22\1\0\40\22\16\0\1\22\7\0\12\56"+
    "\u0136\0\23\22\15\0\232\22\346\0\304\22\274\0\57\22"+
    "\321\0\107\22\271\0\71\22\7\0\37\22\1\0\12\56"+
    "\146\0\36\22\22\0\60\22\20\0\4\22\14\0\12\56"+
    "\11\0\25\22\5\0\23\22\260\0\100\22\200\0\113\22"+
    "\5\0\1\22\102\0\15\22\100\0\2\22\1\0\1\22"+
    "\34\0\370\22\10\0\363\22\15\0\37\22\61\0\3\22"+
    "\21\0\4\22\10\0\u018c\22\4\0\153\22\5\0\15\22"+
    "\3\0\11\22\7\0\12\22\146\0\125\22\1\0\107\22"+
    "\1\0\2\22\2\0\1\22\2\0\2\22\2\0\4\22"+
    "\1\0\14\22\1\0\1\22\1\0\7\22\1\0\101\22"+
    "\1\0\4\22\2\0\10\22\1\0\7\22\1\0\34\22"+
    "\1\0\4\22\1\0\5\22\1\0\1\22\3\0\7\22"+
    "\1\0\u0154\22\2\0\31\22\1\0\31\22\1\0\37\22"+
    "\1\0\31\22\1\0\37\22\1\0\31\22\1\0\37\22"+
    "\1\0\31\22\1\0\37\22\1\0\31\22\1\0\10\22"+
    "\2\0\62\56\55\22\12\0\7\22\2\0\12\56\4\0"+
    "\1\22\u0171\0\54\22\4\0\12\56\6\0\305\22\73\0"+
    "\104\22\7\0\1\22\4\0\12\56\246\0\4\22\1\0"+
    "\33\22\1\0\2\22\1\0\1\22\2\0\1\22\1\0"+
    "\12\22\1\0\4\22\1\0\1\22\1\0\1\22\6\0"+
    "\1\22\4\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\3\22\1\0\2\22\1\0\1\22\2\0\1\22\1\0"+
    "\1\22\1\0\1\22\1\0\1\22\1\0\1\22\1\0"+
    "\2\22\1\0\1\22\2\0\4\22\1\0\7\22\1\0"+
    "\4\22\1\0\4\22\1\0\1\22\1\0\12\22\1\0"+
    "\21\22\5\0\3\22\1\0\5\22\1\0\21\22\104\0"+
    "\327\22\51\0\65\22\13\0\336\22\2\0\u0182\22\16\0"+
    "\u0131\22\37\0\36\22\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\11\1\12\1\13\1\14\1\15\1\0\11\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\20\1\0\2\20"+
    "\1\23\1\0\1\24\1\25\1\0\3\11\1\0\14\15"+
    "\1\26\1\0\1\27\2\30\2\0\1\31\5\15\1\32"+
    "\1\15\1\33\6\15\2\0\1\34\1\23\1\35\1\36"+
    "\3\15\1\37\4\15\1\40\1\26\1\0\1\15\1\41"+
    "\4\15\1\42\1\0\1\43\1\44\2\15\1\45\1\46"+
    "\2\15\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\274\0\274\0\274\0\274\0\274\0\274\0\u0178\0\u01a7"+
    "\0\274\0\274\0\274\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\274\0\274"+
    "\0\u03db\0\274\0\274\0\u040a\0\u0439\0\274\0\u0468\0\u0497"+
    "\0\u04c6\0\274\0\274\0\u04f5\0\274\0\u0524\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\274\0\274"+
    "\0\u0843\0\u0872\0\u08a1\0\274\0\274\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u01d6\0\u098c\0\u01d6\0\u09bb\0\u09ea\0\u0a19\0\u0a48"+
    "\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0872\0\274\0\u01d6\0\u01d6"+
    "\0\u0b33\0\u0b62\0\u0b91\0\u01d6\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\u01d6\0\274\0\u0c7c\0\u0cab\0\u01d6\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u01d6\0\u0d96\0\u01d6\0\u01d6\0\u0dc5\0\u0df4\0\u01d6"+
    "\0\u01d6\0\u0e23\0\u0e52\0\u01d6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\7\1\10\1\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\6\24"+
    "\1\0\1\24\1\25\1\24\1\26\1\24\1\27\1\24"+
    "\1\30\1\24\1\31\1\32\1\33\2\24\1\34\1\24"+
    "\1\35\2\24\1\36\1\24\1\37\1\40\1\0\2\41"+
    "\1\42\1\43\1\44\21\41\1\45\32\41\1\46\1\47"+
    "\1\44\21\41\1\46\30\41\20\0\6\50\1\0\1\50"+
    "\1\51\23\50\63\0\2\7\1\10\1\0\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\6\24\1\0\1\24\1\25\1\24\1\26\1\24"+
    "\1\27\1\24\1\30\1\24\1\31\1\32\1\33\2\24"+
    "\1\34\1\24\1\35\2\24\1\36\1\24\1\52\1\53"+
    "\2\0\2\7\57\0\1\54\74\0\1\20\1\0\1\55"+
    "\1\56\1\57\4\0\1\20\7\0\1\55\6\0\1\56"+
    "\20\0\2\20\6\0\1\55\1\56\2\0\1\20\12\0"+
    "\1\55\6\0\1\56\20\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\23\24\2\0\1\24\2\60\1\0\25\60"+
    "\1\0\26\60\13\0\2\24\3\0\6\24\1\0\1\24"+
    "\1\0\13\24\1\61\6\24\1\62\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\13\24\1\63"+
    "\7\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\11\24\1\64\6\24\1\65\2\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\10\24\1\66\12\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\12\24\1\67\10\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\13\24\1\70\7\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\15\24\1\71\2\24\1\72"+
    "\2\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\7\24\1\73\13\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\13\24\1\74"+
    "\7\24\2\0\1\24\2\41\3\0\21\41\1\0\30\41"+
    "\20\0\6\75\1\0\1\75\1\76\23\75\1\77\2\0"+
    "\2\100\1\0\46\100\1\101\5\100\3\0\1\102\66\0"+
    "\2\50\3\0\6\50\1\0\1\50\1\0\23\50\2\0"+
    "\1\50\2\103\1\0\25\103\1\0\26\103\3\0\1\104"+
    "\76\0\1\55\16\0\1\55\27\0\2\57\3\0\2\57"+
    "\1\0\1\55\1\56\2\0\1\57\1\0\6\57\3\0"+
    "\1\55\6\0\1\56\5\0\2\60\1\0\25\60\1\105"+
    "\26\60\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\13\24\1\106\7\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\17\24\1\107\3\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\20\24\1\110\2\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\13\24\1\111\7\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\12\24\1\112\10\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\3\24\1\113\17\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\17\24\1\114\3\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\12\24\1\115\10\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\10\24\1\116\2\24\1\117\7\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\1\24\1\120"+
    "\21\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\13\24\1\121\7\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\10\24\1\122"+
    "\12\24\2\0\1\24\13\0\2\75\3\0\6\75\1\0"+
    "\1\75\1\0\23\75\2\0\1\75\2\123\1\0\25\123"+
    "\1\0\26\123\13\0\2\124\3\0\2\124\7\0\6\124"+
    "\23\0\1\125\53\0\2\103\1\0\25\103\1\126\26\103"+
    "\13\0\2\24\3\0\6\24\1\0\1\24\1\0\11\24"+
    "\1\127\11\24\2\0\1\24\13\0\2\24\3\0\6\24"+
    "\1\0\1\24\1\0\4\24\1\130\16\24\2\0\1\24"+
    "\13\0\2\24\3\0\6\24\1\0\1\24\1\0\1\24"+
    "\1\131\21\24\2\0\1\24\13\0\2\24\3\0\6\24"+
    "\1\0\1\24\1\0\1\132\22\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\3\24\1\133"+
    "\17\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\6\24\1\134\14\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\21\24\1\135"+
    "\1\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\17\24\1\136\3\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\11\24\1\137"+
    "\11\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\15\24\1\140\5\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\3\24\1\141"+
    "\17\24\2\0\1\24\2\123\1\0\25\123\1\142\26\123"+
    "\13\0\2\143\3\0\2\143\7\0\6\143\33\0\2\24"+
    "\3\0\6\24\1\0\1\24\1\0\11\24\1\144\11\24"+
    "\2\0\1\24\13\0\2\24\3\0\6\24\1\0\1\24"+
    "\1\0\17\24\1\145\3\24\2\0\1\24\13\0\2\24"+
    "\3\0\6\24\1\0\1\24\1\0\4\24\1\146\16\24"+
    "\2\0\1\24\13\0\2\24\3\0\6\24\1\0\1\24"+
    "\1\0\1\147\22\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\4\24\1\150\16\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\10\24\1\151\12\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\17\24\1\152\3\24\2\0"+
    "\1\24\13\0\2\153\3\0\2\153\7\0\6\153\33\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\4\24\1\154"+
    "\16\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\12\24\1\155\10\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\17\24\1\156"+
    "\3\24\2\0\1\24\13\0\2\24\3\0\6\24\1\0"+
    "\1\24\1\0\2\24\1\157\20\24\2\0\1\24\13\0"+
    "\2\24\3\0\6\24\1\0\1\24\1\0\2\24\1\160"+
    "\20\24\2\0\1\24\13\0\2\100\3\0\2\100\7\0"+
    "\6\100\33\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\4\24\1\161\16\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\17\24\1\162\3\24\2\0"+
    "\1\24\13\0\2\24\3\0\6\24\1\0\1\24\1\0"+
    "\4\24\1\163\16\24\2\0\1\24\13\0\2\24\3\0"+
    "\6\24\1\0\1\24\1\0\3\24\1\164\17\24\2\0"+
    "\1\24";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3713];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\10\1\0\2\1\6\11\2\1\3\11\1\1"+
    "\1\0\11\1\2\11\1\1\2\11\1\1\1\0\1\11"+
    "\2\1\1\0\2\11\1\0\1\11\2\1\1\0\15\1"+
    "\1\0\2\11\1\1\2\0\2\11\15\1\2\0\1\1"+
    "\1\11\13\1\1\11\1\0\7\1\1\0\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

     private static final class State {
            final int lBraceCount;
            final int state;

            public State(int state, int lBraceCount) {
                this.state = state;
                this.lBraceCount = lBraceCount;
            }

            @Override
            public String toString() {
                return "yystate = " + state + (lBraceCount == 0 ? "" : "lBraceCount = " + lBraceCount);
            }
        }

    private final Stack<State> states = new Stack<State>();
    private int lBraceCount;

    private int commentStart;
    private int commentDepth;

    private void pushState(int state) {
        states.push(new State(yystate(), lBraceCount));
        lBraceCount = 0;
        yybegin(state);
    }

    private void popState() {
        State state = states.pop();
        lBraceCount = state.lBraceCount;
        yybegin(state.state);
    }

  // tokens for which we need to save current buffer
  private LexToken valueToken(TokenType tokenType) {
    return new LexToken(tokenType, new String(zzBuffer, zzCurrentPos, zzMarkedPos - zzCurrentPos));
  }
  private LexToken token(TokenType tokenType) {
    return new LexToken(tokenType, null);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MarcelJflexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) throws MarcelLexerException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new MarcelLexerException(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  throws MarcelLexerException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  // end of file
    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LexToken nextToken() throws java.io.IOException, MarcelLexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(WHITE_SPACE);
            }
            // fall through
          case 40: break;
          case 2:
            { pushState(STRING); return token(OPEN_QUOTE);
            }
            // fall through
          case 41: break;
          case 3:
            { return token(LPAR);
            }
            // fall through
          case 42: break;
          case 4:
            { return token(RPAR);
            }
            // fall through
          case 43: break;
          case 5:
            { return token(MUL);
            }
            // fall through
          case 44: break;
          case 6:
            { return token(PLUS);
            }
            // fall through
          case 45: break;
          case 7:
            { return token(MINUS);
            }
            // fall through
          case 46: break;
          case 8:
            { return token(DIV);
            }
            // fall through
          case 47: break;
          case 9:
            { return valueToken(INTEGER);
            }
            // fall through
          case 48: break;
          case 10:
            { return token(COLON);
            }
            // fall through
          case 49: break;
          case 11:
            { return token(SEMI_COLON);
            }
            // fall through
          case 50: break;
          case 12:
            { return token(ASSIGNMENT);
            }
            // fall through
          case 51: break;
          case 13:
            { return valueToken(IDENTIFIER);
            }
            // fall through
          case 52: break;
          case 14:
            { return token(BRACKETS_OPEN);
            }
            // fall through
          case 53: break;
          case 15:
            { return token(BRACKETS_CLOSE);
            }
            // fall through
          case 54: break;
          case 16:
            { return valueToken(REGULAR_STRING_PART);
            }
            // fall through
          case 55: break;
          case 17:
            { popState(); yypushback(1); return valueToken(DANGLING_NEWLINE);
            }
            // fall through
          case 56: break;
          case 18:
            { popState(); return token(CLOSING_QUOTE);
            }
            // fall through
          case 57: break;
          case 19:
            { popState(); return valueToken(IDENTIFIER);
            }
            // fall through
          case 58: break;
          case 20:
            { lBraceCount++; return valueToken(LBRACE);
            }
            // fall through
          case 59: break;
          case 21:
            { if (lBraceCount == 0) {
                                             popState();
                                             return token(LONG_TEMPLATE_ENTRY_END);
                                           }
                                           lBraceCount--;
                                           return valueToken(RBRACE);
            }
            // fall through
          case 60: break;
          case 22:
            { pushState(SHORT_TEMPLATE_ENTRY);
                                                        yypushback(yylength() - 1);
                                                        return token(SHORT_TEMPLATE_ENTRY_START);
            }
            // fall through
          case 61: break;
          case 23:
            { pushState(LONG_TEMPLATE_ENTRY); return token(LONG_TEMPLATE_ENTRY_START);
            }
            // fall through
          case 62: break;
          case 24:
            { return valueToken(ESCAPE_SEQUENCE);
            }
            // fall through
          case 63: break;
          case 25:
            { pushState(RAW_STRING); return token(OPEN_QUOTE);
            }
            // fall through
          case 64: break;
          case 26:
            { return token(FUN);
            }
            // fall through
          case 65: break;
          case 27:
            { return token(TYPE_INT);
            }
            // fall through
          case 66: break;
          case 28:
            { int length = yytext().length();
                                    if (length <= 3) { // closing """
                                        popState();
                                        return token(CLOSING_QUOTE);
                                    }
                                    else { // some quotes at the end of a string, e.g. """ "foo""""
                                        yypushback(3); // return the closing quotes (""") to the stream
                                        return valueToken(REGULAR_STRING_PART);
                                    }
            }
            // fall through
          case 67: break;
          case 29:
            { return token(TYPE_BOOL);
            }
            // fall through
          case 68: break;
          case 30:
            { return token(TYPE_BYTE);
            }
            // fall through
          case 69: break;
          case 31:
            { return token(TYPE_LONG);
            }
            // fall through
          case 70: break;
          case 32:
            { return token(TYPE_VOID);
            }
            // fall through
          case 71: break;
          case 33:
            { return token(TYPE_FLOAT);
            }
            // fall through
          case 72: break;
          case 34:
            { return token(TYPE_SHORT);
            }
            // fall through
          case 73: break;
          case 35:
            { return token(TYPE_DOUBLE);
            }
            // fall through
          case 74: break;
          case 36:
            { return token(VISIBILITY_HIDDEN);
            }
            // fall through
          case 75: break;
          case 37:
            { return token(VISIBILITY_PUBLIC);
            }
            // fall through
          case 76: break;
          case 38:
            { return token(VISIBILITY_PRIVATE);
            }
            // fall through
          case 77: break;
          case 39:
            { return token(VISIBILITY_PROTECTED);
            }
            // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
