package com.tambapps.marcel.lexer;

public enum TokenType {
  IDENTIFIER,
  TYPE_INT,
  INTEGER,
  // symbols
  PLUS, MINUS, DIV, MUL, QUOTE, COMMA, QUESTION_MARK, LPAR, RPAR, COLON, SEMI_COLON,
  POWER, NOT, MODULO, AND, EQUAL, NOT_EQUAL, GT, LT, GOE, LOE, OR, ASSIGNEMENT,
  END_OF_FILE
}
