package com.tambapps.marcel.lexer;

public enum TokenType {
  IDENTIFIER,
  WHITE_SPACE,
  // keywords
  TYPE_INT, TYPE_LONG, TYPE_SHORT, TYPE_FLOAT, TYPE_DOUBLE, TYPE_BOOL, TYPE_BYTE, FUN,


// type constants
  INTEGER,


  // symbols
  PLUS, MINUS, DIV, MUL, QUOTE, COMMA, QUESTION_MARK, LPAR, RPAR, COLON, SEMI_COLON,
  POWER, NOT, MODULO, AND, EQUAL, NOT_EQUAL, GT, LT, GOE, LOE, OR, ASSIGNMENT, BRACKETS_OPEN, BRACKETS_CLOSE,
  OPEN_QUOTE, REGULAR_STRING_PART, CLOSING_QUOTE, DANGLING_NEWLINE, ESCAPE_SEQUENCE, LBRACE, RBRACE,
  // shortTemplateEntry: $
  // LONG_TEMPLATE_ENTRY_START: ${}
  SHORT_TEMPLATE_ENTRY_START, LONG_TEMPLATE_ENTRY_START, LONG_TEMPLATE_ENTRY, LONG_TEMPLATE_ENTRY_END,


  // visibilities
  VISIBILITY_PUBLIC, VISIBILITY_PROTECTED, VISIBILITY_HIDDEN, VISIBILITY_PRIVATE,


  END_OF_FILE
}
