package com.tambapps.marcel.lexer;

public enum TokenType {
  IDENTIFIER,
  WHITE_SPACE,
  // keywords
  TYPE_INT, TYPE_LONG, TYPE_SHORT, TYPE_FLOAT, TYPE_DOUBLE, TYPE_BOOL, TYPE_BYTE, FUN,


// type constants
  INTEGER,


  // symbols
  PLUS, MINUS, DIV, MUL, QUOTE, COMMA, QUESTION_MARK, LPAR, RPAR, COLON, SEMI_COLON,
  POWER, NOT, MODULO, AND, EQUAL, NOT_EQUAL, GT, LT, GOE, LOE, OR, ASSIGNMENT, BRACKETS_OPEN, BRACKETS_CLOSE,


  // visibilities
  VISIBILITY_PUBLIC, VISIBILITY_PROTECTED, VISIBILITY_HIDDEN, VISIBILITY_PRIVATE,


  END_OF_FILE
}
